import { Inter } from "next/font/google";
import "./globals.css";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import Header from "@/components/Header";
import Providers from "./providers";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const isDark = true;
  return (
    <html lang="en">
      <body className={inter.className + `${isDark ? " dark" : ""}`}>
        <Providers>
          <Header />
          <div className="py-20 px-10">{children}</div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
